"""add blob

Revision ID: 118b26dacd80
Revises: cf77b24eb0f3
Create Date: 2019-11-30 08:24:38.182682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118b26dacd80'
down_revision = 'cf77b24eb0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contents', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_files', schema=None) as batch_op:
        batch_op.drop_column('contents')

    # ### end Alembic commands ###
