"""added batch_id

Revision ID: 52023a3d723c
Revises: d105a49cc751
Create Date: 2019-12-05 17:23:45.759587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52023a3d723c'
down_revision = 'd105a49cc751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
