"""bool

Revision ID: d105a49cc751
Revises: d136af304dec
Create Date: 2019-11-30 10:32:02.086628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd105a49cc751'
down_revision = 'd136af304dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_files', schema=None) as batch_op:
        batch_op.alter_column('deployed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_files', schema=None) as batch_op:
        batch_op.alter_column('deployed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
