"""add deploy

Revision ID: d136af304dec
Revises: 118b26dacd80
Create Date: 2019-11-30 09:24:51.971669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd136af304dec'
down_revision = '118b26dacd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_files', schema=None) as batch_op:
        batch_op.drop_column('deployed')

    # ### end Alembic commands ###
